@startuml
'Alice-->Bob: Authentication Request
'Bob-->Alice: Authentication Response

:Main Admin: as Admin
User --> (Register)
Admin--> (Register)
(Register) --> (Submit Details)
note left of User: This is user
note right of Admin : This is Admin

@enduml